# Generated by Django 3.0.6 on 2020-06-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('template_name', models.CharField(max_length=100)),
                ('visit_dt', models.DateTimeField()),
                ('ip', models.CharField(max_length=100)),
                ('signup_email', models.EmailField(max_length=254)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_content', models.CharField(max_length=1000)),
            ],
        ),
    ]
